apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dep-ngnix 
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: app-nginx-container
        image: nginx
        ports:
        - containerPort: 80
