apiVersion: v1
kind: Service
metadata:
  name: lb-nginx
  labels:
    service: lb-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 31000
    targetPort: 80
    protocol: TCP
  selector:
      app: app-nginx
